config/routes.rb
Rails.application.routes.draw do

  resources :alerts

  resources :rules do
    get "feed", on: :collection
  end

  resources :source_fields

  resources :sources do
    resources :source_rules
  end

  devise_for :users

  resources :users do
    get 'reset_password/:email' => :reset_password, on: :collection, as: :reset_password
    post '/admin/create' => :create, on: :collection, as: :admin_create
    get 'notications' => :notications, on: :collection
  end

  root 'dashboard#index'

end

app/models/source.rb
class Source < ActiveRecord::Base

  belongs_to :user
  has_many :source_fields
  has_many :source_rules

  accepts_nested_attributes_for :source_fields

  validates :source_id, presence: true, length: { minimum: 10  }, uniqueness: {scope: [:user_id]}

  after_save :create_or_update_source, :create_or_update_rule
  after_create :create_kafka_topic

  HBASE_CLIENT = Stargate::Client.new("http://54.68.26.107:12323")

  def api_source_id
    "#{self.user.api_key}::#{self.source_id}"
  end

  def create_kafka_topic
    system "#{ENV['KAFKA_HOME']}/bin/kafka-topics.sh --topic #{api_source_id} --create --partitions 1 --replication-factor 1 --zookeeper localhost:2181"
  end

  def publish_success_count
    published_rows.select {|col| col.name.include? "success"}.count #rescue 0
  end

  def publish_failure_count
    published_rows.select {|col| col.name.include? "failed"}.count #rescue 0
  end

  def published_rows
    @rows ||= HBASE_CLIENT.show_row('apiRequestTable', api_source_id).columns rescue []
  end

  def create_or_update_source
    # HBASE_CLIENT.create_row('source', "#{api_source_id}", Time.now.to_i, {name: "metadata:metadata", value: {name: self.name, event_type: self.event_type}.to_json})
    HBASE_CLIENT.create_row('source', "#{api_source_id}", Time.now.to_i, {name: "fields:fields", value: source_fields.collect(&:as_json).to_json})
  end

  def create_or_update_rule
    HBASE_CLIENT.create_row('source_rule', "#{api_source_id}", Time.now.to_i, {name: "rule:rule", value: source_rules.collect(&:as_json).to_json})
  end

end

#
# val theget = new Get(Bytes.toBytes("5022d9105e2a0132e43c0a5f603a4ac0::ask4prasath"))
# theget.addFamily(Bytes.toBytes("success"))
# theget.setMaxVersions(45)
# val result = apiRequestTable.get(theget)
# val stringresult = Bytes.toString(value)
#
# import org.apache.hadoop.hbase.client.{Delete, HBaseAdmin, HTable, Put, Result => HBaseResult, Scan}
#
#
#
# val scan = new Scan(Bytes.toBytes("5022d9105e2a0132e43c0a5f603a4ac0::ask4prasath"))
# scan.addFamily(Bytes.toBytes("success"))
# val scanner = apiRequestTable.getScanner(scan)
# scanner.next.list.size
#
#
# val scan = new Scan(Bytes.toBytes("5022d9105e2a0132e43c0a5f603a4ac0::ask4prasath"))
# scan.addFamily(Bytes.toBytes("failed"))
# val scanner = apiRequestTable.getScanner(scan)
# scanner.next.list.size
#
#

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  # GET /sources
  # GET /sources.json
  def index
    @sources = current_user.sources
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
    5.times { @source.source_fields.build }
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(source_params)
    @source.user = current_user

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1
  # PATCH/PUT /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source.destroy
    respond_to do |format|
      format.html { redirect_to sources_url, notice: 'Source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_params
      params.require(:source).permit!
    end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/_form.html.erb
<div class="row">
  <div class="col-sm-12">

    <div class="panel panel-default">
      <div class="panel-body">

<%= nested_form_for(@source, html: {class: "form-horizontal"}) do |f| %>
  <% if @source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
      <% @source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <label class="col-sm-2 control-label" for="field-1">Event Type</label>
      <div class="col-sm-10">
        <%= f.select :event_type, ["JSON"], {}, class: 'form-control' %>
      </div> <br><br><br>

      <label class="col-sm-2 control-label" for="field-1">Source Id</label>
      <div class="col-sm-10">
        <%= f.text_field :source_id, class: 'form-control' %>
      </div> <br><br><br>

      <label class="col-sm-2 control-label" for="field-1">Validation</label>
      <div class="col-sm-10">
        <%= f.check_box :validation, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group-separator"></div>


    <%= f.fields_for :source_fields do |task_form| %>

        <div class="form-group">
          <label class="col-sm-2 control-label" for="field-1">Source Fields (<%== task_form.link_to_remove "Remove" %>)</label>
          <div class="col-sm-10">
            Name: <%= task_form.text_field :key_name, class: "text" %>
            Field Type: <%= task_form.select :field_type, ["String", "Integer", "Float", "Timestamp"], {prompt: 'Select Field Type'}, class: "source_type" %>
            <span class="required" style="display: none;">Required:</span>
            <%= task_form.check_box :required, style: "display: none;" %>
            <span class="min" style="display: none;">Min value:</span>
            <%= task_form.text_field :min_length, style: "display: none;"  %>
            <span class="max" style="display: none;">Max value:</span>
            <%= task_form.text_field :max_length, style: "display: none;"  %>
            <span class="space" style="display: none;">Space Allowed:</span>
            <%= task_form.check_box :space_allowed, style: "display: none;"  %>
            <span class="default" style="display: none;">Default Value:</span>
            <%= task_form.text_field :default_value, style: "display: none;" %>
          </div>
          <br><br><br>
        </div>

    <% end %>

    <p><%= f.link_to_add "Add Source fields", :source_fields, class: 'btn btn-success' %></p>
    <div class="form-group-separator"></div>

    <%= f.submit 'Submit', class: 'btn btn-success' %>
<% end %>


<%= javascript_include_tag :defaults, "nested_form" %>

<script>
  var value;
  $(document.body).on("change", ".source_type", function(){
      typeValue = $(this).val()
      $.each($(this).siblings(), function( index, value ) {

        if(typeValue === "String") {
            if($(value).attr("name") === undefined) {
               if($(value).attr("class").match(/required/)) {
                    $(value).show()
               } else if($(value).attr("class").match(/min/)) {
                    $(value).show()
               } else if($(value).attr("class").match(/max/)) {
                    $(value).show()
               } else if($(value).attr("class").match(/default/)) {
                    $(value).hide()
               } else if($(value).attr("class").match(/space/)) {
                    $(value).show()
               }
            } else {
               if($(value).attr("name").match(/required/)) {
                    $(value).show()
               } else if($(value).attr("name").match(/min/)) {
                    $(value).show()
               } else if($(value).attr("name").match(/max/)) {
                    $(value).show()
               } else if($(value).attr("name").match(/default/)) {
                    $(value).hide()
               } else if($(value).attr("name").match(/space/)) {
                    $(value).show()
               }
            }
        } else if(typeValue === "Integer") {
           if($(value).attr("name") === undefined) {
                if($(value).attr("class").match(/required/)) {
                   $(value).show()
               } else if($(value).attr("class").match(/min/)) {
                    $(value).show()
               } else if($(value).attr("class").match(/max/)) {
                    $(value).show()
               } else if($(value).attr("class").match(/max/)) {
                    $(value).hide()
               } else if($(value).attr("class").match(/default/)) {
                    $(value).show()
               } else if($(value).attr("class").match(/space/)) {
                    $(value).hide()
               }
            } else {

               if($(value).attr("name").match(/required/)) {
                   $(value).show()
               } else if($(value).attr("name").match(/min/)) {
                    $(value).show()
               } else if($(value).attr("name").match(/max/)) {
                    $(value).show()
               } else if($(value).attr("name").match(/max/)) {
                    $(value).hide()
               } else if($(value).attr("name").match(/default/)) {
                    $(value).show()
               } else if($(value).attr("name").match(/space/)) {
                    $(value).hide()
               }
            }
        } else if(typeValue === "Float") {
            if($(value).attr("name") === undefined) {
               if($(value).attr("class").match(/required/)) {
                    $(value).hide()
               } else if($(value).attr("class").match(/min/)) {
                    $(value).show()
               } else if($(value).attr("class").match(/max/)) {
                    $(value).show()
               } else if($(value).attr("class").match(/max/)) {
                    $(value).hide()
               } else if($(value).attr("class").match(/default/)) {
                    $(value).show()
               } else if($(value).attr("class").match(/space/)) {
                    $(value).hide()
               }
            } else {
               if($(value).attr("name").match(/required/)) {
                    $(value).hide()
               } else if($(value).attr("name").match(/min/)) {
                    $(value).show()
               } else if($(value).attr("name").match(/max/)) {
                    $(value).show()
               } else if($(value).attr("name").match(/max/)) {
                    $(value).hide()
               } else if($(value).attr("name").match(/default/)) {
                    $(value).show()
               } else if($(value).attr("name").match(/space/)) {
                    $(value).hide()
               }
            }

        } else if(typeValue === "Timestamp") {
             if($(value).attr("name") === undefined) {
               if($(value).attr("name").match(/required/)) {
                   $(value).show()
               } else if($(value).attr("class").match(/min/)) {
                    $(value).hide()
               } else if($(value).attr("class").match(/max/)) {
                    $(value).hide()
               } else if($(value).attr("class").match(/max/)) {
                    $(value).hide()
               } else if($(value).attr("class").match(/default/)) {
                    $(value).hide()
               } else if($(value).attr("class").match(/space/)) {
                    $(value).hide()
               }
            } else {
               if($(value).attr("name").match(/required/)) {
                   $(value).show()
               } else if($(value).attr("name").match(/min/)) {
                    $(value).hide()
               } else if($(value).attr("name").match(/max/)) {
                    $(value).hide()
               } else if($(value).attr("name").match(/max/)) {
                    $(value).hide()
               } else if($(value).attr("name").match(/default/)) {
                    $(value).hide()
               } else if($(value).attr("name").match(/space/)) {
                    $(value).hide()
               }
           }
        } else {
             $(value).hide();
        }
      });
  })
</script>

</div>
</div>
</div>
</div>

app/views/sources/edit.html.erb
<div class="page-title">

  <div class="title-env">
    <h1 class="title">Source</h1>
    <p class="description">Edit source</p>
  </div>

  <div class="breadcrumb-env">

    <ol class="breadcrumb bc-1">
      <li>
        <a href="/"><i class="fa-home"></i>Home</a>
      </li>
      <li class="active">
        <strong>Source</strong>
      </li>
    </ol>

  </div>

</div>

<%= render 'form' %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<div class="page-title">

  <div class="title-env">
    <h1 class="title">Sources</h1>

    <p class="description">Add or remove sources</p>
  </div>

  <div class="breadcrumb-env">

    <ol class="breadcrumb bc-1">
      <li>
        <a href="/"><i class="fa-home"></i>Home</a>
      </li>
      <li class="active">
        <strong>Manage Admins</strong>
      </li>
    </ol>

  </div>

</div>


<div class="row">
  <div class="col-sm-12">
    <div class="xe-widget xe-counter">

      <table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Source Id</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @sources.each do |source| %>
      <tr>
        <td><%= source.source_id %></td>
        <td><%= link_to 'New Rule', new_source_source_rule_path(source) %></td>
        <td><%= link_to 'Show', source %></td>
        <td><%= link_to 'Edit', edit_source_path(source) %></td>
        <td><%= link_to 'Destroy', source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>
</div>


<%= link_to 'New Source', new_source_path, class: 'btn btn-primary' %>

app/views/sources/new.html.erb
<div class="page-title">

  <div class="title-env">
    <h1 class="title">Source</h1>
    <p class="description">Add new source</p>
  </div>

  <div class="breadcrumb-env">

    <ol class="breadcrumb bc-1">
      <li>
        <a href="/"><i class="fa-home"></i>Home</a>
      </li>
      <li class="active">
        <strong>Source</strong>
      </li>
    </ol>

  </div>

</div>

<%= render 'form' %>

<%= link_to 'Back', sources_path %>

app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-sm-12">
  <div class="xe-widget xe-counter">
    <div class="xe-label">
        <p>
            <b>Publishing url:</b> http://54.69.164.109:8080/publish <br /><br />
            <b>Api key:</b> <%= current_user.api_key %><br /><br />
            <b>Source id:</b> <%= @source.source_id %><br /><br />
            <b>Source fields:</b> <%= @source.source_fields.collect(&:key_name).join(", ") %>
        </p>

      <ul class="list-group">

        <li class="list-group-item">Source Rules</li>

        <% @source.source_rules.each do |rule| %>


              <li class="list-group-item"><%= rule.name %>  <%= rule.action %>  <%= rule.value %></li>


         <% end %>
      </ul>

    </div>
  </div>
</div>
<%= link_to 'New Rule', new_source_source_rule_path(@source), class: 'btn' %>
<%= link_to 'Edit', edit_source_path(@source) %> |
<%= link_to 'Back', sources_path %>