config/routes.rb
Rails.application.routes.draw do

  resources :alerts

  resources :rules do
    get "feed", on: :collection
  end

  resources :source_fields

  resources :sources do
    resources :source_rules
  end

  devise_for :users

  resources :users do
    get 'reset_password/:email' => :reset_password, on: :collection, as: :reset_password
    post '/admin/create' => :create, on: :collection, as: :admin_create
    get 'notications' => :notications, on: :collection
  end

  root 'dashboard#index'

end

app/models/source_field.rb
class SourceField < ActiveRecord::Base
  belongs_to :source

  validates :key_name, presence: true, length: { in: 3..40 }, uniqueness: {scope: [:source_id]}
  validates :field_type, presence: true

end

app/controllers/source_fields_controller.rb
class SourceFieldsController < ApplicationController
  before_action :set_source_field, only: [:show, :edit, :update, :destroy]

  # GET /source_fields
  # GET /source_fields.json
  def index
    @source_fields = SourceField.all
  end

  # GET /source_fields/1
  # GET /source_fields/1.json
  def show
  end

  # GET /source_fields/new
  def new
    @source_field = SourceField.new
  end

  # GET /source_fields/1/edit
  def edit
  end

  # POST /source_fields
  # POST /source_fields.json
  def create
    @source_field = SourceField.new(source_field_params)

    respond_to do |format|
      if @source_field.save
        format.html { redirect_to @source_field, notice: 'Source field was successfully created.' }
        format.json { render :show, status: :created, location: @source_field }
      else
        format.html { render :new }
        format.json { render json: @source_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /source_fields/1
  # PATCH/PUT /source_fields/1.json
  def update
    respond_to do |format|
      if @source_field.update(source_field_params)
        format.html { redirect_to @source_field, notice: 'Source field was successfully updated.' }
        format.json { render :show, status: :ok, location: @source_field }
      else
        format.html { render :edit }
        format.json { render json: @source_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /source_fields/1
  # DELETE /source_fields/1.json
  def destroy
    @source_field.destroy
    respond_to do |format|
      format.html { redirect_to source_fields_url, notice: 'Source field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source_field
      @source_field = SourceField.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_field_params
      params.require(:source_field).permit(:key_name, :field_type, :source_id)
    end
end

app/helpers/source_fields_helper.rb
module SourceFieldsHelper
end

app/views/source_fields/_form.html.erb
<%= form_for(@source_field) do |f| %>
  <% if @source_field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source_field.errors.count, "error") %> prohibited this source_field from being saved:</h2>

      <ul>
      <% @source_field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key_name %><br>
    <%= f.text_field :key_name %>
  </div>
  <div class="field">
    <%= f.label :field_type %><br>
    <%= f.text_field :field_type %>
  </div>
  <div class="field">
    <%= f.label :source_id %><br>
    <%= f.text_field :source_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/source_fields/edit.html.erb
<h1>Editing source_field</h1>

<%= render 'form' %>

<%= link_to 'Show', @source_field %> |
<%= link_to 'Back', source_fields_path %>

app/views/source_fields/index.html.erb
<h1>Listing source_fields</h1>

<table>
  <thead>
    <tr>
      <th>Key name</th>
      <th>Field type</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @source_fields.each do |source_field| %>
      <tr>
        <td><%= source_field.key_name %></td>
        <td><%= source_field.field_type %></td>
        <td><%= source_field.source %></td>
        <td><%= link_to 'Show', source_field %></td>
        <td><%= link_to 'Edit', edit_source_field_path(source_field) %></td>
        <td><%= link_to 'Destroy', source_field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Source field', new_source_field_path %>

app/views/source_fields/new.html.erb
<h1>New source_field</h1>

<%= render 'form' %>

<%= link_to 'Back', source_fields_path %>

app/views/source_fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key name:</strong>
  <%= @source_field.key_name %>
</p>

<p>
  <strong>Field type:</strong>
  <%= @source_field.field_type %>
</p>

<p>
  <strong>Source:</strong>
  <%= @source_field.source %>
</p>

<%= link_to 'Edit', edit_source_field_path(@source_field) %> |
<%= link_to 'Back', source_fields_path %>